name: Daily Commit

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Random commits (20 to 500) with random delays
        run: |
          git config user.name "ujwal6-eng"
          git config user.email "anandujwal6@gmail.com"

          # Commit count random: 20-500
          max_commits=$(( ( RANDOM % 481 ) + 20 ))
          echo "Aaj ke commits: $max_commits"

          for ((i=1; i<=max_commits; i++)); do
            # Random delay 1s to 180s (3 mins)
            delay=$(( ( RANDOM % 180 ) + 1 ))

            echo "$(date) - commit $i (delay ${delay}s)" >> update.txt
            git add update.txt
            git commit -m "Auto commit $i"

            echo "Sleeping ${delay} seconds..."
            sleep $delay
          done

      - name: Push commits
        run: git push
